export const route = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  userProfile: "/userProfile",
  favorite: "/favorite",
  blogDetail: "/blog",
  confirmEmail: "/confirm-email",

  admin: "/admin",
  dashboard: "dashboard",
  discountManagement: "discount-management",

  accountManagement: "account-management",
  orderManagement: "order-management",
  boxManagement: "box-management",
  boxItemManagement: "box-items-management",
  brandManagement: "brand-management",
  boxImageManagement: "box-image-management",
  boxOptionManagement: "box-option-management",

  staff: "/staff",
  feedbackManagement: "feedback-management",
  blogManagement: "blog-management",
  chatWithCustomer: "chat-box",

  product: "/product",
  productDetail: "/product/detail",
  boxItemPage: "/box-item",
  boxItemDetail: "/box-item/detail",
  cart: "cart",
  checkout: "/checkout",
  blog: "/blog",
  orderSuccess: "/order-success",
  paymentReturn: "/payment-return",
  onlineBlindBox: "/online-blindbox",
};
